# Generated by Django 3.1 on 2021-04-24 10:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0007_auto_20210424_0959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 24, 10, 2, 59, 684252)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 24, 10, 2, 59, 683838)),
        ),
        migrations.AlterField(
            model_name='elektro',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 24, 10, 2, 59, 684578)),
        ),
        migrations.AlterField(
            model_name='snippet',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 24, 10, 2, 59, 683406)),
        ),
        migrations.AlterField(
            model_name='tarif',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 24, 10, 2, 59, 684905)),
        ),
    ]
